apiVersion: apps/v1
kind: Deployment
metadata:
  name: koaxhome
spec:
  selector:
    matchLabels:
      app: koaxhome
  template:
    metadata:
      labels:
        app: koaxhome
    spec:
      containers:
      - name: app
        image: iluhins/koaxhome:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: koaxhome-svc
spec:
  selector:
    app: koaxhome
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
