apiVersion: apps/v1
kind: Deployment
metadata:
  name: koax_home
spec:
  selector:
    matchLabels:
      app: koax_home
  template:
    metadata:
      labels:
        app: koax_home
    spec:
      containers:
      - name: app
        image: illuhins/koax_home:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: koax_home_svc
spec:
  selector:
    app: koax_home
  ports:
  - port: 80
    targetPort: 80

